[package]
name = "systasis"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Statically wired dependency injection with checked, nonblocking value access"
publish = false

[workspace]
members = ["systasis-macros"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[lints]
workspace = true

[features]
default = ["std"]
std = ["thiserror/std", "dep:parking_lot"]
resolve_unchecked = ["systasis-macros/resolve_unchecked"]

[dependencies]
systasis-macros = { path = "systasis-macros", version = "0.1.0" }
parking_lot = { version = "0.12.5", default-features = false, features = ["send_guard"], optional = true }
thiserror = { version = "2.0.20", default-features = false }
spin = { version = "0.12.2", default-features = false, features = ["rwlock", "lock_api"] }
